# iOS Toolchain File
set(CMAKE_SYSTEM_NAME iOS CACHE STRING "" FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 18.0 CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "" FORCE)

# Prevent any macOS deployment target from being set
set(CMAKE_MACOSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)
unset(MACOSX_DEPLOYMENT_TARGET CACHE)
unset(ENV{MACOSX_DEPLOYMENT_TARGET})

# Force these flags for all C/CXX compilation
set(CMAKE_C_FLAGS_INIT "-miphoneos-version-min=18.0")
set(CMAKE_CXX_FLAGS_INIT "-miphoneos-version-min=18.0")

# Disable bitcode (deprecated in Xcode 14+)
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE NO)

# Skip code signing for libraries
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO)

# Ensure we're using iOS SDK
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
