# tvOS Toolchain File
set(CMAKE_SYSTEM_NAME tvOS)
set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET 18.0 CACHE STRING "")

# Force tvOS SDK
set(CMAKE_OSX_SYSROOT appletvos CACHE STRING "")

# Prevent macOS deployment target from being set
unset(CMAKE_OSX_DEPLOYMENT_TARGET_DEFAULT)
set(MACOSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)

# C/C++ Standards
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 20)

# Compiler flags
set(CMAKE_C_FLAGS_INIT "-fembed-bitcode")
set(CMAKE_CXX_FLAGS_INIT "-fembed-bitcode")

# Skip code signing for libraries
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED "NO")
